---
apiVersion: v1
kind: Service
metadata:
  name: eth-geth-tx
  labels:
    app: eth-geth-tx
spec:
  selector:
    app: eth-geth-tx
  type: ClusterIP
  ports:
    - name: rpc
      port: 8545
    - name: ws
      port: 8546
